if (SERVER) then
AddCSLuaFile("autorun/cat_init.lua")
AddCSLuaFile("cat_client.lua")
AddCSLuaFile("cat_shared.lua")
include("cat_shared.lua")
include("cat_CONFIG.lua")
include("sv_catmotd.lua")
include("sv_chat.lua")
AddCSLuaFile("cl_chat.lua")
AddCSLuaFile("cl_catmotd.lua")
include("cat_core.lua")
include("plugins/sv_slay.lua")
include("plugins/sv_ignite.lua")
include("plugins/sv_extinguish.lua")
include("plugins/sv_health.lua")
include("plugins/sv_armor.lua")
include("plugins/sv_kick.lua")
include("plugins/sv_ban.lua")
include("plugins/sv_freeze.lua")
include("plugins/sv_unfreeze.lua")
include("plugins/sv_god.lua")
include("plugins/sv_ungod.lua")
include("plugins/sv_cleanuserprops.lua")
include("plugins/sh_screencap.lua")
AddCSLuaFile("plugins/sh_screencap.lua")
include("plugins/sv_bring.lua")
include("plugins/sv_goto.lua")
include("plugins/sh_FUCKMYEYES.lua")
AddCSLuaFile("plugins/sh_FUCKMYEYES.lua")
include("plugins/sh_blind.lua")
AddCSLuaFile("plugins/sh_blind.lua")
include("plugins/sv_cloak.lua")
include("plugins/sv_uncloak.lua")
include("plugins/sh_ragdoll.lua")
AddCSLuaFile("plugins/sh_ragdoll.lua")
AddCSLuaFile("cat_menu.lua")
include("plugins/sv_setaccess.lua")
include("plugins/sv_noclip.lua")
include("plugins/sv_rocket.lua")
include("plugins/sv_playerpickup.lua")
include("plugins/sv_cleardecals.lua")
include("plugins/sv_rcon.lua")
include("plugins/sv_setspeed.lua")
include("plugins/sv_gimp.lua")
include("plugins/sv_cleanserver.lua")
include("plugins/sv_mute.lua")
include("plugins/sv_grammar.lua")
include("plugins/sv_give.lua")
include("plugins/sv_cexec.lua")
include("plugins/sv_changemap.lua")
include("plugins/sv_strip.lua")
include("plugins/sv_slapo.lua")
include("plugins/sv_unban.lua")




end