if (CLIENT) then
	include("cl_catpp.lua")			
	include("cl_chat.lua")
	include("plugins/sh_screencap.lua")
	include("plugins/sh_seizure.lua")
	include("plugins/sh_blind.lua")
	include("plugins/sh_ragdoll.lua")
	include("cat_menu.lua")
	include("cl_catmotd.lua")
	include("cat_shared.lua")
	include("plugins/sh_devmode.lua")
	include("plugins/sh_voicemute.lua")
	include("plugins/sh_observerban.lua")
	include("cat_CONFIG.lua")
end